version: '3'

services:
  postgres:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'postgres'
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  api_nest:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - postgres
    restart: always
    environment:
      DB_HOST: postgres
      DB_PORT: 5432

volumes:
  pg-data:
